version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./afone_web/docker/env/.dev.env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - afone-network

  django_back_afone:
    build:
      context: ./afone_web
    container_name: afone_django
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    env_file:
      - ./afone_web/docker/env/.dev.env
    volumes:
      - static_volume:/app/static
      - ./afone_web:/app
    networks:
      - afone-network

  nginx:
    image: nginx:latest
    container_name: afone_nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "8080:80"
    depends_on:
      - django_back_afone
    networks:
      - afone-network

volumes:
  pg_data:
  static_volume:

networks:
  afone-network:
    driver: bridge
